[project]
name = "tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-cloud-texttospeech>=2.33.0",
    "kittentts",
    "pandas>=2.3.2",
    "pyperclip>=1.9.0",
    "python-dotenv>=1.2.1",
]

[tool.uv.sources]
kittentts = { url = "https://github.com/KittenML/KittenTTS/releases/download/0.1/kittentts-0.1.0-py3-none-any.whl" }
